- name: Deploy Docker Stack
  hosts: localhost
  become: yes
  vars:
    destination_directory:  "{{ lookup('hashi_vault', 'secret=secret/data/common:DDIR') }}"
  tasks:
    - name: Create a Vault directory if it does not exist already
      ansible.builtin.file:
        path: "{{ destination_directory }}"
        state: directory
        mode: '0755'

    - name: Retrieve environment file from Vault
      set_fact: 
        env_file : "{{ lookup('hashi_vault', 'secret=secret/data/config') }}"
      changed_when: false
      
    - name: Fetch GitHub Details from Vault
      set_fact: 
        USERNAME: "{{ lookup('hashi_vault', 'secret=secret/data/github:USERNAME') }}"
        PAT: "{{ lookup('hashi_vault', 'secret=secret/data/github:PAT') }}"
      changed_when: false

    - name: Authenticate with GitHub Container Registry
      docker_login:
        registry_url: docker.pkg.github.com
        username: "{{ USERNAME }}"
        password: "{{ PAT }}"
        reauthorize: yes

    - name: Download Config File
      shell:
        curl -o ./config.json -L https://raw.githubusercontent.com/Samagra-Development/ai-tools/restructure/config.json
      args:
        chdir: "{{ destination_directory }}"
    
    - name: Download Script that generates Docker file
      shell:
        curl -o generate_independent_docker.sh https://raw.githubusercontent.com/Samagra-Development/ai-tools/restructure/generate_independent_docker.sh
      args:
        chdir: "{{ destination_directory }}"
    
    - name: Generate sample.env from Vault data
      copy:
        dest: "{{ destination_directory }}/sample.env"
        content: |
          {% for key, value in env_file.items() %}
          {{ key }}={{ value }}
          {% endfor %}  
      vars:
        env_file: "{{ env_file }}"

    - name: Install jq
      apt:
        name: jq
        state: present

    - name: Generate Docker-Compose File
      shell: "./generate_independent_docker.sh"
      args:
        chdir: "{{ destination_directory }}"
      
    - name: Pull Docker Images
      shell: docker-compose -f ./docker-compose-independent-generated.yaml pull
      args:
        chdir: "{{ destination_directory }}"

    - name: Deploy Docker Images to Docker Swarm
      shell: docker stack deploy -c ./docker-compose-independent-generated.yaml aitools_stack
      args:
        chdir: "{{ destination_directory }}"
