- name: Deploy Docker Stack
  hosts: swarm_manager
  become: yes
  tasks:
    - name: Install Docker SDK for Python
      pip:
        name: docker
      become_user: root
      become: yes
      become_method: sudo
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    - name: Convert Docker Compose to Docker Stack
      command: docker stack deploy -c ./docker-compose.yaml ansible_stack
      become_user: "{{ ansible_user }}"