- name: Deploy Docker Stack
  hosts: swarm_manager
  become: yes
  vars:
    destination_directory: <install_path>
    github_repo: <github_repo>
    github_PAT: <PAT>
  tasks:
    - name: Authenticate with GitHub Container Registry
      docker_login:
        registry_url: ghcr.io
        username: {{  github_repo  }}
        password: {{ github_PAT  }}
        reauthorize: yes

    - name: Download Files
      shell:
        curl -o ./config.json -L https://raw.githubusercontent.com/Samagra-Development/ai-tools/restructure/config.json
        curl -o ./generate_independent_docker.sh -L https://raw.githubusercontent.com/Samagra-Development/ai-tools/restructure/generate_independent_docker.sh
      args:
        chdir: "{{ destination_directory }}"


    - name: Run commands in the cloned directory
      shell:     
        ./generate_independent_docker.sh
      args:
        chdir: "{{ destination_directory }}"
      become_user: root
      become: yes
      become_method: sudo
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    - name: Retrieve environment file from Vault
      vars:
        vault_address: <address>
        vault_token: <access_token>
        vault_secret_path: <location>
        vault_field: <file>
      shell: vault kv get -field=value -format=json ${{ value_secret_path }}/${{ value_field }} > ./sample_file.env
      changed_when: false
      args:
        chdir: "{{ destination_directory }}"
      environment:
        VAULT_ADDR: "{{ vault_address }}"
        VAULT_TOKEN: "{{ vault_token }}"

    - name: Convert Docker Compose to Docker Stack
      command: docker stack deploy -c ./docker-compose-independent-generated.yaml ansible_stack
      become_user: "{{ ansible_user }}"
      environment: './sample_file.env'
      args:
        chdir: "{{ destination_directory }}"